services:
  app:
    build: .
    ports:
      - "80:80"
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "cl@ssH3lpers"
        ACCEPT_EULA: "Y"